//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.29 at 03:36:38 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.big-oh.net/hello/jaxb")
package hello.jaxb.xsd2java;
